version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X wzjk-cli/internal/version.Version={{.Version}}
    binary: wzjk-cli

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - name: wzjk-cli
    repository:
      owner: sandakacn
      name: homebrew-wzjk-cli
      branch: main
    directory: Formula
    homepage: https://gitee.com/sandaka/wzjk-cli
    description: CLI tool for wzjk
    license: MIT
    install: |
      bin.install "wzjk-cli"
    test: |
      system "#{bin}/wzjk-cli", "--version"
